version: '2.1'
services:
   web:
      build: .
      ports:
         - "8080:8080"
      depends_on:
         - db
      networks:
         - mt-network

   db:
      image: mysql:8
      environment:
         - MYSQL_DATABASE=db
         - MYSQL_USER=user      
         - MYSQL_PASSWORD=password
         - MYSQL_ROOT_PASSWORD=password
      ports: 
       - '3306:3306'
      expose: 
       - '3306'
      volumes:
         - ./sql/insert_table.sql:/docker-entrypoint-initdb.d/insert_table.sql
         - my-db:/var/lib/mysql
      networks:
         - mt-network
    
volumes:
  my-db:
  
networks:
   mt-network:
      driver: bridge